<a href="https://colab.research.google.com/github/parinitha672/Banglore-Tech-Salary-Decoder/blob/main/Live_Project_Parinitha_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing the libraries
import numpy as np
import pandas as pd

In [3]:
#loading the dataset
df=pd.read_csv("bangalore_tech_salaries.csv")
#display the first rows
df.head()

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
0,BLR0065,DS,6,49.4,32.4 LPA,Ola,Unicorn,"JIRA, JavaScript, Spring Boot, Figma, NumPy, A...",HSR Layout,Tier-1,2022,Remote
1,BLR0080,DevOps,0,9.7,NaN,Walmart Labs,MNC,"Tableau, Python, Figma, JavaScript, TensorFlow",Electronic City,2,2024,Remote
2,BLR0166,SDE Backend,6,"3,360,000",24.2 LPA,Postman,Mid-size,"Agile, Excel, GCP, MongoDB, Java, ML",Whitefield,Tier-1,2023,Hybrid
3,BLR0219,SDE Frontend,8,41.4 LPA,30.3,Amazon India,MNC,"PyTorch, Redis, System Design",MG Road,Tier-2,2022,Work from Office
4,BLR0491,Product Lead,5,"3,640,000",30.6 LPA,QuickPay AI,early-stage,"Tableau, Deep Learning, Agile",Whitefield,Tier-2,2023,Onsite

In [6]:
#checking the shape
df.shape

(1015, 12)

In [7]:
#checking the missing values
df.isnull().sum()

Employee_ID         0
Role                0
years_exp           0
Current_CTC         0
Previous_CTC      200
Company             0
company_TYPE        0
Skills             27
Location           20
Education_Tier      0
Joining_Year        0
Work_Mode           0
dtype: int64

In [8]:
#removing duplicate rows
df.drop_duplicates()

,Employee_ID,Role,years_exp,Current_CTC,Previous_CTC,Company,company_TYPE,Skills,Location,Education_Tier,Joining_Year,Work_Mode
0,BLR0065,DS,6,49.4,32.4 LPA,Ola,Unicorn,"JIRA, JavaScript, Spring Boot, Figma, NumPy, A...",HSR Layout,Tier-1,2022,Remote
1,BLR0080,DevOps,0,9.7,NaN,Walmart Labs,MNC,"Tableau, Python, Figma, JavaScript, TensorFlow",Electronic City,2,2024,Remote
2,BLR0166,SDE Backend,6,"3,360,000",24.2 LPA,Postman,Mid-size,"Agile, Excel, GCP, MongoDB, Java, ML",Whitefield,Tier-1,2023,Hybrid
3,BLR0219,SDE Frontend,8,41.4 LPA,30.3,Amazon India,MNC,"PyTorch, Redis, System Design",MG Road,Tier-2,2022,Work from Office
4,BLR0491,Product Lead,5,"3,640,000",30.6 LPA,QuickPay AI,early-stage,"Tableau, Deep Learning, Agile",Whitefield,Tier-2,2023,Onsite
...,...,...,...,...,...,...,...,...,...,...,...,...
1010,BLR0824,Product Designer,2,17.6,12.4,Zoho,Mid-size,"React, SQL, ML, Deep Learning, Java",Jayanagar,Tier-2,2022,WFH
1011,BLR0792,Product Lead,4,₹40.2 LPA,26.6,HCL,MNC,"Excel, Java, Deep Learning, Python, JavaScript",Whitefield,Tier 2,2021,Work from Office
1012,BLR0209,BI Analyst,1,8.6 LPA,6.0 LPA,EdMint,Early-stage,"PyTorch, System Design, MongoDB, JIRA, PowerBI...",NaN,2,2024,Hybrid
1013,BLR0788,PM,2,27.6,17.4,Zomato,Unicorn,"Azure, Kafka, Excel",Bellandur,Tier-3,2023,Remote
1014,BLR0905,DA,4,₹20.3 LPA,15.4 LPA,Capgemini,MNC,"Deep Learning, JavaScript, NumPy",Marathahalli,Tier 2,2020,WFH

In [10]:
#printing columns names
print(df.columns)

Index(['Employee_ID', 'Role ', 'years_exp', 'Current_CTC', 'Previous_CTC',
       'Company', 'company_TYPE', 'Skills', 'Location', 'Education_Tier',
       'Joining_Year', 'Work_Mode'],
      dtype='object')

In [12]:
#standardize the  comapny type values
df["company_TYPE"]=df["company_TYPE"].str.upper()

In [13]:
print(df["company_TYPE"])

0           UNICORN
1               MNC
2          MID-SIZE
3               MNC
4       EARLY-STAGE
           ...
1010       MID-SIZE
1011            MNC
1012    EARLY-STAGE
1013        UNICORN
1014            MNC
Name: company_TYPE, Length: 1015, dtype: object

In [44]:
#rename the columns
df=df.rename(columns={"Employee_ID":"employee_id","Role":"role","years_exp":"years_exp","Current_CTC":"currenct_ctc","Previous_CTC":"previous_ctc","Company":"comapany","company_TYPE":"company_type","Location":"location","Education_Tier":"education_tier","Joining_Year":"joining_year","Work_Mode":"work_mode"})

In [45]:
#printing new column names
print(df.columns)

Index(['employee_id', 'Role ', 'years_exp', 'currenct_ctc', 'previous_ctc',
       'comapny', 'company_type', 'Skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

In [23]:
#standardize company type
df["company_type"]=df["company_type"].str.upper()

In [24]:
print(df["company_type"].unique())

['UNICORN' 'MNC' 'MID-SIZE' 'EARLY-STAGE']

In [34]:
#standardize company type
df["company_type"]=df["company_type"].replace({
    "unicorn":"Unicorn",
    "UNICORN":"Unicorn",
    "mnc":"MNC",
    "MNC":"MNC",
    "mid-size":"Mid-size",
    "MID-SIZE":"Mid-size",
    "early-stage":"Early-stage",
    "EARLY-STAGE":"Early-stage"
})

In [35]:
print(df["company_type"].unique())

['Unicorn' 'MNC' 'Mid-size' 'Early-stage']

In [36]:
#standardize education tier
df["education_tier"]=df["education_tier"].replace({
    "T1":"Tier 1",
    "1":"Tier 1",
    "Tier-1":"Tier 1",
    "T2":"Tier 2",
    "2":"Tier 2",
    "Tier-2":"Tier 2",
    "T3":"Tier 3",
    "3":"Tier 3",
    "Tier-3":"Tier 3"
})

In [37]:
print(df["education_tier"].unique())

['Tier 1' 'Tier 2' 'Tier 3']

In [41]:
print(df.columns)

Index(['employee_id', 'Role ', 'years_exp', 'currenct_ctc', 'previous_ctc',
       'comapny', 'company_type', 'Skills', 'location', 'education_tier',
       'joining_year', 'work_mode'],
      dtype='object')

In [46]:
#printing role names
print(df['Role '].unique())

['DS' 'DevOps' 'SDE Backend' 'SDE Frontend' 'Product Lead'
 'Product Manager' 'Site Reliability Engineer' 'DA' 'UI/UX' 'SDE-Frontend'
 'UI Designer' 'ML Engineer' 'Frontend Dev' 'Data Scientist'
 'Full Stack Engineer' 'Designer' 'Product Designer' 'BA'
 'Frontend Engineer' 'BI Analyst' 'Backend Dev' 'Sr PM' 'FE' 'SDE-Backend'
 'Data Analyst' 'Business Analyst' 'Backend Developer'
 'Business Systems Analyst' 'Data Science Engineer' 'FullStack' 'BE'
 'Frontend Developer' 'Backend Engineer' 'UX Designer' 'Infra Engineer'
 'PM' 'SDE FS' 'DevOps Engineer' 'Analytics Engineer' 'Fullstack Dev'
 'SDE Full-Stack' 'SRE']

In [51]:
#standadrize role names
df['Role '] = df['Role '].replace({
    "backend SD": "SDE Backend",
    "backend dev": "SDE Backend",
    "backend developer": "SDE Backend",
    "backend engineer": "SDE Backend",
    "BE": "SDE Backend",

    "frontend": "SDE Frontend",
    "frontend dev": "SDE Frontend",
    "frontend developer": "SDE Frontend",
    "frontend engineer": "SDE Frontend",

    "full stack": "SDE Full-Stack",
    "full stack dev": "SDE Full-Stack",
    "full stack engineer": "SDE Full-Stack",

    "DS": "Data Scientist",
    "data scientist": "Data Scientist",
    "data science engineer": "Data Scientist",
    "ML engineering": "Data Scientist",

    "DA": "Data Analyst",
    "data analyst": "Data Analyst",
    "BI analyst": "Data Analyst",
    "analytics engineer": "Data Analyst",

    "DevOps": "DevOps Engineer",
    "DevOps engineer": "DevOps Engineer",
    "infra engineer": "DevOps Engineer",
    "site reliability engineer": "DevOps Engineer",
    "SRE": "DevOps Engineer",

    "PM": "Product Manager",
    "product manager": "Product Manager",
    "product lead": "Product Manager",

    "UI/UX": "UI/UX Designer",
    "UI designer": "UI/UX Designer",
    "UX designer": "UI/UX Designer",
    "designer": "UI/UX Designer",
    "product designer": "UI/UX Designer",

    "business analyst": "Business Analyst",
    "business system analyst": "Business Analyst"
})

In [52]:
print(df['Role '].unique())

['Data Scientist' 'DevOps Engineer' 'SDE Backend' 'SDE Frontend'
 'Product Lead' 'Product Manager' 'Site Reliability Engineer'
 'Data Analyst' 'UI/UX Designer' 'SDE-Frontend' 'UI Designer'
 'ML Engineer' 'Frontend Dev' 'Full Stack Engineer' 'Designer'
 'Product Designer' 'BA' 'Frontend Engineer' 'BI Analyst' 'Backend Dev'
 'Sr PM' 'FE' 'SDE-Backend' 'Business Analyst' 'Backend Developer'
 'Business Systems Analyst' 'Data Science Engineer' 'FullStack'
 'Frontend Developer' 'Backend Engineer' 'UX Designer' 'Infra Engineer'
 'SDE FS' 'Analytics Engineer' 'Fullstack Dev' 'SDE Full-Stack']

In [53]:
#convert Current_CTC
def parse_ctc(ctc):
    if pd.isna(ctc):
        return np.nan

    ctc = str(ctc).replace("₹", "").replace("LPA", "").replace(",", "").strip()

    try:
        value = float(ctc)


        if value > 100000:
            value = value / 100000

        return value
    except:
        return np.nan

In [61]:
df["current_CTC_clean"]=df["currenct_ctc"].apply(parse_ctc)

In [70]:
print(df["current_CTC_clean"])==df["currenct_ctc"].apply(parse_ctc)

0       49.4
1        9.7
2       33.6
3       41.4
4       36.4
        ...
1010    17.6
1011    40.2
1012     8.6
1013    27.6
1014    20.3
Name: current_CTC_clean, Length: 1015, dtype: float64

0       False
1       False
2       False
3       False
4       False
        ...
1010    False
1011    False
1012    False
1013    False
1014    False
Name: currenct_ctc, Length: 1015, dtype: bool

In [74]:
# Convert Previous_CTC values into numeric LPA format
df["previous_CTC_Clean"] = df["previous_ctc"].apply(parse_ctc)

In [75]:
df=df.drop_duplicates()

In [77]:
print(df.duplicated().sum())

0

In [78]:
#count missing values in each column
print(df.isnull().sum())

employee_id             0
Role                    0
years_exp               0
currenct_ctc            0
previous_ctc          194
comapny                 0
company_type            0
Skills                 27
location               19
education_tier          0
joining_year            0
work_mode               0
current_CTC_clean       0
previous_CTC_Clean    194
dtype: int64

In [79]:
#check data types
print(df.dtypes)

employee_id            object
Role                   object
years_exp               int64
currenct_ctc           object
previous_ctc           object
comapny                object
company_type           object
Skills                 object
location               object
education_tier         object
joining_year            int64
work_mode              object
current_CTC_clean     float64
previous_CTC_Clean    float64
dtype: object

In [80]:
#verify standard role names
print(df['Role '].value_counts())

Role
DevOps Engineer              74
Data Scientist               64
Product Manager              55
Data Analyst                 50
SDE Backend                  42
BA                           41
Business Analyst             35
Site Reliability Engineer    33
Business Systems Analyst     32
ML Engineer                  31
Product Lead                 31
Data Science Engineer        30
BI Analyst                   28
Designer                     28
Sr PM                        26
Frontend Developer           24
SDE FS                       24
UI/UX Designer               23
Product Designer             23
Analytics Engineer           22
Full Stack Engineer          22
SDE-Backend                  21
SDE Frontend                 20
FullStack                    20
UI Designer                  20
Infra Engineer               20
Frontend Engineer            19
Backend Dev                  19
UX Designer                  19
Frontend Dev                 18
Backend Engineer             17
SDE Full-Stack               16
Backend Developer            15
Fullstack Dev                14
SDE-Frontend                 12
FE                           12
Name: count, dtype: int64

In [81]:
#verify standardize comapny nmaes
print(df['company_type'].value_counts())

company_type
MNC            342
Mid-size       257
Unicorn        207
Early-stage    194
Name: count, dtype: int64

In [83]:
# Verify standardized education tiers
print(df["education_tier"].value_counts())

education_tier
Tier 2    500
Tier 3    306
Tier 1    194
Name: count, dtype: int64

In [86]:
#Q3.1 - Calculate CTC statistics for each role
role_stats = df.groupby('Role ')["current_CTC_clean"].agg(["mean", "median", "min", "max"])

role_stats = role_stats.sort_values(by="median", ascending=False)

print(role_stats)

                                mean     median   min       max
Role
Sr PM                      35.400000  31.500000  10.8  65.50000
Product Manager            35.418182  31.400000  13.8  80.10000
Product Lead               30.783870  31.100000  12.0  55.10000
Backend Engineer           30.605882  31.100000   9.9  55.10000
ML Engineer                30.335484  27.500000  10.0  64.50000
Data Science Engineer      28.356667  25.650000  14.3  75.60000
FE                         24.108333  25.300000  11.5  31.10000
SDE FS                     28.612500  24.600000  11.5  70.90000
Fullstack Dev              21.821429  24.550000   9.0  33.40000
Frontend Developer         23.604167  24.300000  11.0  39.40000
Infra Engineer             22.610000  23.450000   9.2  45.50000
SDE Full-Stack             28.568750  23.050000  10.7  71.70000
Data Scientist             25.879687  22.850000  10.9  73.50000
Site Reliability Engineer  23.333333  22.200000   9.9  55.00000
UI/UX Designer             21.565217  22.000000   6.2  44.10000
SDE Backend                22.538095  21.600000   7.9  46.00000
DevOps Engineer            23.416216  21.499995   8.8  60.30000
Analytics Engineer         20.909091  21.400000   6.8  37.90000
Frontend Engineer          20.852632  21.000000   8.1  39.40000
Business Systems Analyst   22.071875  20.900000   6.8  52.20000
SDE-Backend                24.071428  20.600000   9.3  49.80000
Full Stack Engineer        25.390909  20.500000  12.0  49.80000
BA                         22.824390  20.500000   7.6  52.70000
Frontend Dev               25.144444  20.250000   8.9  84.40000
UI Designer                19.925000  19.500000   8.6  44.50000
SDE Frontend               21.005000  19.200000   6.7  41.40000
Product Designer           21.526087  19.000000  10.9  55.70000
Backend Dev                20.400000  18.000000   9.2  46.80000
UX Designer                23.268421  18.000000   6.6  63.30000
Designer                   19.203571  17.900000   7.1  43.80000
FullStack                  21.570000  17.600000   8.9  45.30000
BI Analyst                 16.782142  16.450000   5.2  36.29999
Backend Developer          19.626667  16.400000   8.0  51.30000
Business Analyst           20.577143  16.400000   6.8  44.90000
Data Analyst               17.150000  16.300000   5.6  43.40000
SDE-Frontend               17.133333  16.250000  12.1  27.30000

In [95]:
## Q3.2 - Group SDE Backend employees by experience and calculate median CTC
sde = df[df['Role '] == "SDE Backend"].copy()

In [99]:
median_ctc = sde.groupby("experience_group")["current_CTC_clean"].median()

print(median_ctc)

experience_group
0-1    11.65
2-3    21.40
4-5    25.20
6+     36.20
Name: current_CTC_clean, dtype: float64

/tmp/ipykernel_1081/1615415604.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_ctc = sde.groupby("experience_group")["current_CTC_clean"].median()

In [98]:
# Create experience categories
bins = [0, 1, 3, 5, 100]
labels = ["0-1", "2-3", "4-5", "6+"]

sde.loc[:, "experience_group"] = pd.cut(
    sde["years_exp"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [104]:
median_ctc = sde.groupby("experience_group")['current_CTC_clean'].median()

print(median_ctc)

experience_group
0-1    11.65
2-3    21.40
4-5    25.20
6+     36.20
Name: current_CTC_clean, dtype: float64

/tmp/ipykernel_1081/2986993415.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_ctc = sde.groupby("experience_group")['current_CTC_clean'].median()

In [109]:
## Q3.3 - Compare median CTC of employees with and without specific skills
# Display all unique skills
print(df['Skills'].unique())

['JIRA, JavaScript, Spring Boot, Figma, NumPy, Agile, Docker'
 'Tableau, Python, Figma, JavaScript, TensorFlow'
 'Agile, Excel, GCP, MongoDB, Java, ML' 'PyTorch, Redis, System Design'
 'Tableau, Deep Learning, Agile'
 'Azure, JIRA, PostgreSQL, System Design, React, Figma'
 'Spring Boot, PyTorch, GCP, Docker, Azure' 'React, Docker, Python'
 'Azure, Docker, JavaScript, SQL, TensorFlow'
 'Azure, PowerBI, Kafka, Sketch, React, Tableau'
 'GCP, MongoDB, Spring Boot, PostgreSQL, Node.js, Agile'
 'PostgreSQL, Microservices, Deep Learning'
 'Kafka, Deep Learning, Node.js, SQL, Redis, ML'
 'GCP, TensorFlow, Java, PyTorch'
 'GCP, Tableau, JIRA, React, Python, NumPy' 'React, PyTorch, Pandas'
 'Figma, PowerBI, JavaScript'
 'Agile, PostgreSQL, JavaScript, Azure, Docker'
 'GCP, JIRA, React, JavaScript, Kafka'
 'System Design, Redis, React, Docker, PowerBI, TensorFlow, PyTorch'
 'Pandas, React, PowerBI, System Design, GCP, Figma'
 'MongoDB, Docker, PyTorch, System Design'
 'MongoDB, Spring Boot, GCP, Java, System Design, Python'
 'NumPy, Kubernetes, Deep Learning, PostgreSQL' 'JIRA, Kafka, Pandas'
 'SQL, JavaScript, Azure, Deep Learning'
 'JIRA, JavaScript, ML, AWS, NumPy, System Design, TensorFlow'
 'Sketch, Pandas, Microservices, Kafka, PowerBI, GCP, Node.js'
 'Deep Learning, Java, PowerBI, Spring Boot'
 'PowerBI, System Design, Agile, Node.js'
 'GCP, Figma, React, Spring Boot, System Design, Redis, JavaScript'
 'TensorFlow, Azure, Figma, Node.js, Kafka, Kubernetes, PowerBI'
 'TensorFlow, Java, Tableau' 'Azure, MongoDB, Deep Learning, React, Agile'
 'Excel, Tableau, Docker, Redis, JIRA, Python, Node.js'
 'Deep Learning, PyTorch, Kubernetes, Figma, AWS, Spring Boot, Azure'
 'PostgreSQL, AWS, Agile, JIRA, MongoDB, Kubernetes, SQL'
 'GCP, Docker, Figma, Azure, JIRA, Spring Boot, Agile' 'ML, MongoDB, GCP'
 'Python, Kubernetes, Azure, Redis'
 'AWS, Node.js, JavaScript, SQL, Deep Learning, Redis'
 'Spring Boot, Kubernetes, Figma, PyTorch, Azure, TensorFlow'
 'NumPy, PostgreSQL, System Design, SQL, AWS, Docker'
 'Spring Boot, Azure, Excel' 'Tableau, React, AWS, Figma, Java, Node.js'
 'Excel, Java, Sketch, SQL, React, Node.js, PostgreSQL'
 'Spring Boot, PowerBI, JavaScript, Deep Learning'
 'Redis, PowerBI, Spring Boot, ML, AWS, Deep Learning, JIRA'
 'PyTorch, GCP, Kubernetes, TensorFlow'
 'JavaScript, MongoDB, JIRA, Spring Boot, Deep Learning, System Design, GCP'
 'Agile, Node.js, Sketch, AWS'
 'Spring Boot, AWS, Figma, React, PyTorch, Excel'
 'Microservices, PostgreSQL, Java, Spring Boot, Figma, Kubernetes, SQL'
 'Agile, PyTorch, Python, PowerBI, MongoDB, Kafka, Tableau'
 'Redis, SQL, GCP, Figma, Java, PostgreSQL'
 'GCP, Figma, Tableau, Azure, Kubernetes'
 'Docker, Deep Learning, Excel, Node.js, Redis, Java'
 'Microservices, ML, Spring Boot, Java, Tableau'
 'AWS, Tableau, React, MongoDB, PowerBI, Kafka'
 'Figma, PowerBI, Docker, Deep Learning, GCP, Java, NumPy'
 'Java, System Design, SQL, NumPy, AWS, ML, Tableau'
 'AWS, Spring Boot, JavaScript, Tableau'
 'Deep Learning, MongoDB, Node.js, Python, Excel, ML, PostgreSQL'
 'Excel, Kubernetes, Python, Redis, Sketch' 'Deep Learning, ML, PowerBI'
 'Deep Learning, PowerBI, SQL'
 'JavaScript, Figma, MongoDB, Kafka, Redis, Docker'
 'ML, Figma, Microservices, PostgreSQL, TensorFlow, MongoDB'
 'Pandas, Spring Boot, PyTorch' 'Tableau, Azure, Pandas'
 'SQL, Docker, Excel, Kubernetes' 'PyTorch, GCP, ML'
 'Python, Node.js, Figma' 'NumPy, Azure, TensorFlow'
 'ML, Kafka, Azure, React, Python, Tableau, PowerBI'
 'Node.js, Microservices, ML, Python' 'Excel, Figma, ML, PowerBI'
 'Excel, TensorFlow, JavaScript, Python' 'Agile, Azure, Java'
 'Docker, ML, Tableau, Node.js, TensorFlow, Microservices, Python'
 'Pandas, PowerBI, Spring Boot, React, Kafka'
 'JIRA, MongoDB, System Design' 'Agile, React, PyTorch, Sketch, MongoDB'
 'Kafka, Tableau, TensorFlow, Node.js, Kubernetes'
 'Tableau, Kubernetes, MongoDB, PostgreSQL'
 'Tableau, MongoDB, Node.js, Microservices, JavaScript, Docker'
 'Node.js, NumPy, Pandas, JIRA, Kubernetes'
 'JavaScript, Spring Boot, React, Pandas, Figma'
 'PyTorch, ML, NumPy, Figma' 'Tableau, Docker, Kubernetes, JavaScript'
 'JavaScript, Pandas, NumPy, Microservices, Figma, System Design, JIRA'
 'Python, Azure, TensorFlow, Deep Learning'
 'Figma, SQL, Deep Learning, ML'
 'Sketch, System Design, MongoDB, Python, Redis'
 'Azure, Spring Boot, SQL, NumPy, Python, TensorFlow'
 'Pandas, Docker, Java, Deep Learning'
 'Spring Boot, Tableau, TensorFlow, Redis, JIRA'
 'Redis, Spring Boot, Figma, React, ML'
 'Python, Agile, Kubernetes, Deep Learning, Docker, JIRA, PowerBI'
 'JIRA, MongoDB, Redis, Java, Deep Learning'
 'Node.js, PostgreSQL, MongoDB, Kubernetes, ML, GCP, Redis'
 'Python, MongoDB, Kubernetes, Redis'
 'Kubernetes, ML, JavaScript, Java, Python, Docker' nan
 'Spring Boot, React, PostgreSQL, Pandas, Kafka, Redis'
 'React, System Design, Figma, Kubernetes, ML'
 'PostgreSQL, JIRA, Node.js, Microservices, Kubernetes, System Design, Java'
 'SQL, Figma, Kubernetes, PostgreSQL, Deep Learning, Python'
 'ML, JIRA, Kubernetes'
 'Kubernetes, Azure, TensorFlow, Microservices, PostgreSQL'
 'Microservices, NumPy, Node.js, Sketch, Java, Python'
 'Agile, Pandas, JIRA, Python, PyTorch, PowerBI'
 'JavaScript, JIRA, Pandas, React, Kubernetes, MongoDB, Java'
 'Azure, AWS, Sketch' 'Agile, System Design, Microservices, PowerBI'
 'MongoDB, PostgreSQL, Redis, Python' 'PyTorch, Agile, Kafka'
 'Sketch, Node.js, GCP, Kubernetes, Redis'
 'System Design, Spring Boot, Java, PyTorch, Sketch'
 'JavaScript, Deep Learning, PowerBI, Excel, Sketch, Azure, PostgreSQL'
 'Tableau, Python, JIRA, System Design'
 'Java, System Design, TensorFlow, Docker, React, Python'
 'React, PostgreSQL, Node.js, Pandas, MongoDB, Agile'
 'NumPy, Azure, PyTorch, PostgreSQL, System Design, Microservices, AWS'
 'Spring Boot, Agile, PyTorch, Excel, JIRA, Kubernetes'
 'Docker, Node.js, Kubernetes'
 'Pandas, Sketch, Java, Redis, Figma, Spring Boot'
 'System Design, Docker, Azure, GCP'
 'System Design, Sketch, AWS, Kubernetes, Docker'
 'Kubernetes, React, MongoDB, Docker, Python, Java'
 'Azure, Sketch, Docker, Excel, Node.js'
 'React, Kafka, PowerBI, Excel, Java, Agile'
 'Java, PowerBI, React, JavaScript'
 'MongoDB, NumPy, Tableau, PostgreSQL, Python'
 'TensorFlow, PyTorch, SQL, MongoDB, Pandas'
 'Spring Boot, Docker, PowerBI, GCP, Agile'
 'React, Agile, Node.js, Pandas, Python, Kubernetes, Java'
 'JavaScript, Excel, Redis, Kafka, JIRA, Node.js'
 'System Design, Spring Boot, Redis, TensorFlow, ML'
 'PostgreSQL, MongoDB, Pandas, JIRA, Java, Agile'
 'Microservices, Node.js, Docker, AWS, MongoDB, Python, Agile'
 'Agile, ML, Node.js'
 'Deep Learning, Node.js, JavaScript, React, Tableau, TensorFlow'
 'Node.js, Pandas, JIRA, Spring Boot'
 'PowerBI, Pandas, System Design, TensorFlow, PyTorch' 'SQL, GCP, Python'
 'Spring Boot, Docker, Deep Learning, Microservices'
 'Docker, Microservices, GCP, React' 'AWS, ML, Deep Learning, Redis, Java'
 'Spring Boot, GCP, PyTorch, Figma, Docker, AWS'
 'TensorFlow, System Design, Redis, Deep Learning, Spring Boot, React, Tableau'
 'JavaScript, PowerBI, Tableau, ML, Kubernetes, Microservices'
 'PostgreSQL, MongoDB, Kafka, SQL, AWS' 'Figma, Kubernetes, AWS, Pandas'
 'TensorFlow, Sketch, Deep Learning, PowerBI, Node.js'
 'Excel, Python, System Design, Spring Boot, Deep Learning'
 'Sketch, Excel, Spring Boot, Deep Learning'
 'NumPy, ML, PostgreSQL, PowerBI, Azure, Node.js'
 'PyTorch, Redis, PowerBI'
 'Java, NumPy, TensorFlow, MongoDB, Node.js, Figma, AWS'
 'Agile, PowerBI, Redis, Azure, Kubernetes, Deep Learning'
 'Pandas, Spring Boot, React, AWS, Microservices'
 'Figma, Sketch, PostgreSQL' 'Python, React, System Design, SQL'
 'Java, Azure, Figma, Agile, Excel, SQL, PowerBI' 'Redis, React, Python'
 'Deep Learning, Microservices, SQL, NumPy'
 'Deep Learning, Pandas, Excel, Node.js, ML, System Design, React'
 'Node.js, System Design, Excel, SQL, PowerBI'
 'Node.js, Spring Boot, ML, Tableau, Agile, PyTorch'
 'GCP, Deep Learning, Agile, Kubernetes' 'Kafka, NumPy, PyTorch'
 'Excel, System Design, Kafka, Python, JIRA' 'Java, Python, PostgreSQL'
 'React, AWS, System Design, Sketch, Java' 'Kafka, JavaScript, SQL'
 'Spring Boot, Pandas, Kubernetes, ML'
 'Microservices, Agile, Excel, PowerBI, Node.js, Java, Figma'
 'SQL, Agile, Kafka, PowerBI'
 'Agile, JIRA, NumPy, Azure, React, Kafka, Python'
 'Python, PowerBI, Redis, Deep Learning' 'Node.js, GCP, System Design'
 'GCP, AWS, NumPy, SQL'
 'PyTorch, Microservices, Azure, Java, System Design'
 'MongoDB, Azure, PyTorch, Kafka, Microservices, Tableau, Java'
 'Kafka, TensorFlow, SQL, React, Agile, JIRA, Spring Boot'
 'Redis, Azure, Kafka'
 'Tableau, Redis, Agile, PyTorch, Kubernetes, PowerBI, Node.js'
 'Excel, Spring Boot, System Design' 'Microservices, Azure, TensorFlow'
 'GCP, Java, Deep Learning, NumPy, TensorFlow, PostgreSQL'
 'Figma, Java, System Design, MongoDB, Azure' 'ML, Figma, PostgreSQL, SQL'
 'Figma, React, JIRA' 'Java, Node.js, NumPy'
 'JIRA, PowerBI, PostgreSQL, Excel'
 'JavaScript, Sketch, AWS, Python, Kubernetes'
 'PowerBI, AWS, Azure, Redis, Node.js, TensorFlow, JavaScript'
 'Kubernetes, Spring Boot, TensorFlow, Sketch, React, Docker, Deep Learning'
 'Node.js, Figma, SQL, AWS' 'JavaScript, NumPy, AWS, TensorFlow'
 'Azure, Kafka, Redis'
 'Docker, PostgreSQL, MongoDB, Redis, PyTorch, Azure, Tableau'
 'Redis, System Design, Java, JavaScript'
 'React, AWS, Figma, SQL, Redis, System Design, Docker'
 'React, Pandas, Agile, System Design, AWS, Kubernetes, PowerBI'
 'JavaScript, Microservices, Kafka, JIRA, React, PostgreSQL'
 'Agile, Excel, JIRA, React' 'PyTorch, System Design, Agile, React, Figma'
 'PowerBI, Deep Learning, ML, PyTorch'
 'PyTorch, Pandas, Microservices, SQL'
 'AWS, Java, Kafka, Excel, System Design'
 'Sketch, Docker, Microservices, Pandas'
 'Node.js, PyTorch, SQL, GCP, Azure'
 'AWS, Azure, React, Sketch, Java, Docker' 'GCP, Sketch, Excel'
 'React, JavaScript, Kubernetes'
 'Docker, Azure, Redis, Deep Learning, TensorFlow, Spring Boot, Python'
 'Figma, Java, Node.js, React' 'Excel, JavaScript, Sketch, SQL, Node.js'
 'Tableau, ML, Java'
 'Sketch, Docker, SQL, PostgreSQL, Deep Learning, React, Kafka'
 'Figma, Python, ML, Sketch'
 'Java, Sketch, System Design, PyTorch, MongoDB, AWS'
 'ML, Figma, SQL, Spring Boot, NumPy, TensorFlow'
 'Pandas, Java, Excel, MongoDB, ML'
 'Java, JavaScript, Tableau, Node.js, Docker'
 'JIRA, Pandas, MongoDB, Python, Microservices, ML, PowerBI'
 'GCP, Spring Boot, Node.js, React, PowerBI, PyTorch'
 'PostgreSQL, AWS, GCP, Sketch'
 'Deep Learning, Sketch, JavaScript, GCP, Docker, Excel'
 'Docker, Microservices, Deep Learning, Kafka, PostgreSQL, Tableau'
 'JIRA, Java, Tableau' 'Sketch, Python, ML, PostgreSQL'
 'Kubernetes, MongoDB, Sketch, Microservices, GCP, Tableau, System Design'
 'JIRA, React, Java, PowerBI, NumPy, Redis'
 'Sketch, Python, System Design, PyTorch, Node.js, MongoDB'
 'Tableau, SQL, Kafka, ML' 'Kubernetes, PowerBI, GCP'
 'Excel, Redis, Deep Learning'
 'GCP, JIRA, AWS, Python, Java, Node.js, SQL'
 'Excel, Spring Boot, MongoDB, JavaScript, Node.js, PyTorch'
 'MongoDB, Agile, Node.js' 'Agile, Python, React, Figma'
 'Sketch, Figma, NumPy, Excel'
 'React, System Design, Figma, ML, JavaScript, Node.js, Tableau'
 'Docker, ML, Figma, PostgreSQL'
 'System Design, MongoDB, Microservices, Sketch, Java, Figma'
 'Spring Boot, SQL, GCP, TensorFlow, Java'
 'Kubernetes, Docker, Redis, Spring Boot'
 'Redis, Kubernetes, Deep Learning' 'Docker, Excel, Java'
 'Agile, Spring Boot, TensorFlow, ML'
 'Docker, React, JavaScript, Deep Learning, NumPy'
 'Redis, MongoDB, Deep Learning, AWS, Node.js'
 'Java, PyTorch, Spring Boot' 'JavaScript, Spring Boot, Excel'
 'PyTorch, Excel, Pandas'
 'Figma, Spring Boot, Microservices, JavaScript, Azure, React'
 'React, Redis, GCP, NumPy, Azure, Kubernetes'
 'Agile, PyTorch, TensorFlow, Node.js, Figma, Python, React'
 'Kubernetes, PostgreSQL, Node.js, Java'
 'React, Excel, Spring Boot, Java, Docker, Tableau'
 'React, PowerBI, Kubernetes'
 'Excel, Kafka, Docker, MongoDB, Tableau, Python'
 'Sketch, PostgreSQL, PyTorch, MongoDB, AWS'
 'NumPy, SQL, Tableau, Python, Agile, JavaScript'
 'Kafka, Tableau, System Design, Excel, PostgreSQL'
 'AWS, Node.js, Java, MongoDB' 'Microservices, Kafka, TensorFlow, AWS'
 'Microservices, PowerBI, NumPy, React, Pandas, Python'
 'Python, SQL, JIRA, GCP, Deep Learning, TensorFlow'
 'NumPy, AWS, System Design' 'JavaScript, Node.js, React'
 'NumPy, Microservices, AWS, Redis, Excel'
 'Spring Boot, PostgreSQL, React, Deep Learning, AWS, Microservices'
 'Figma, Excel, Pandas' 'Python, Java, AWS, Redis, GCP, Pandas'
 'System Design, JavaScript, Microservices, Redis, Node.js'
 'React, Agile, Spring Boot, Pandas, PostgreSQL, SQL, Redis'
 'Deep Learning, PostgreSQL, Tableau, Docker, Spring Boot'
 'Java, Node.js, NumPy, Deep Learning, PostgreSQL, System Design, Kafka'
 'MongoDB, SQL, Java, Kubernetes, Pandas, JavaScript, Deep Learning'
 'PowerBI, Kafka, Python' 'Deep Learning, PyTorch, Kubernetes'
 'NumPy, Kafka, Python, Excel, PostgreSQL'
 'Java, Python, Sketch, System Design, Deep Learning' 'Python, Java, AWS'
 'Pandas, System Design, Azure, GCP, PyTorch, Java, Spring Boot'
 'Pandas, JavaScript, ML' 'AWS, Figma, Kubernetes, Python'
 'Azure, Microservices, Figma, JIRA'
 'Node.js, AWS, MongoDB, Spring Boot, NumPy, Microservices'
 'Azure, Tableau, Pandas, GCP, SQL, Node.js'
 'PostgreSQL, System Design, Tableau, TensorFlow, SQL, Agile'
 'PowerBI, Azure, Kubernetes, Kafka, Agile, JIRA, PyTorch'
 'Spring Boot, Java, Agile, Figma'
 'Kafka, Node.js, AWS, PostgreSQL, JavaScript, Figma, Azure'
 'PowerBI, Sketch, Tableau, PostgreSQL, React'
 'PostgreSQL, Java, Microservices, Python'
 'Tableau, Python, NumPy, Agile, AWS'
 'Python, Kafka, Spring Boot, AWS, Microservices' 'ML, Java, TensorFlow'
 'Pandas, System Design, Docker, AWS, ML'
 'PowerBI, Tableau, Kafka, Figma, Node.js, Deep Learning, Python'
 'Redis, Java, ML, MongoDB'
 'MongoDB, Redis, Microservices, JIRA, System Design'
 'PyTorch, GCP, System Design' 'Redis, Python, MongoDB, PyTorch, GCP, ML'
 'Docker, Java, AWS'
 'MongoDB, TensorFlow, Node.js, JIRA, Pandas, Deep Learning'
 'Kafka, Microservices, Deep Learning, ML, System Design'
 'JavaScript, Agile, Azure, Tableau, React, Deep Learning'
 'Spring Boot, System Design, Agile, Node.js'
 'Pandas, System Design, Spring Boot' 'React, JavaScript, Deep Learning'
 'Figma, Docker, NumPy, Java, Azure, Python, Redis'
 'MongoDB, Node.js, Deep Learning, Kubernetes, NumPy, JIRA'
 'Microservices, Deep Learning, SQL, Agile, Spring Boot, Node.js'
 'Azure, NumPy, PowerBI, Redis, Tableau, PostgreSQL'
 'Tableau, Azure, Kubernetes, Python' 'Sketch, JIRA, TensorFlow'
 'Spring Boot, Tableau, Java, PowerBI, Deep Learning, Python, MongoDB'
 'PostgreSQL, Kubernetes, JIRA' 'Pandas, Redis, TensorFlow, MongoDB, JIRA'
 'System Design, Kubernetes, Node.js, Spring Boot, Tableau, Figma'
 'Redis, System Design, React, PowerBI' 'Figma, System Design, React, AWS'
 'PyTorch, MongoDB, Tableau, Excel, Microservices, Kafka, System Design'
 'Figma, PowerBI, Redis, PostgreSQL, MongoDB, React'
 'JIRA, MongoDB, Python, AWS' 'AWS, PowerBI, Deep Learning, Java, Sketch'
 'Tableau, Figma, PostgreSQL, ML, Deep Learning, Node.js, React'
 'MongoDB, SQL, PowerBI, Pandas'
 'Node.js, PostgreSQL, NumPy, GCP, Deep Learning, Azure'
 'Pandas, JIRA, Excel, TensorFlow'
 'Deep Learning, JavaScript, TensorFlow, ML, SQL'
 'NumPy, PyTorch, Spring Boot, Kubernetes' 'Java, AWS, Agile'
 'GCP, Spring Boot, Microservices, React, JIRA, AWS, Sketch'
 'MongoDB, JavaScript, System Design' 'Node.js, Java, Excel, Figma'
 'Microservices, Docker, SQL'
 'SQL, Kafka, Figma, Python, Java, Agile, System Design'
 'Kafka, JavaScript, Pandas, Spring Boot, Tableau, Microservices, Agile'
 'Pandas, PyTorch, TensorFlow, NumPy' 'JIRA, Redis, Figma, Kubernetes'
 'Azure, System Design, Java, Python, Pandas' 'Java, Pandas, NumPy'
 'Spring Boot, Excel, React, Figma'
 'System Design, Sketch, AWS, Kubernetes, Tableau' 'React, Redis, Docker'
 'Azure, Tableau, Excel'
 'Java, Figma, MongoDB, Kubernetes, SQL, PyTorch, TensorFlow'
 'Pandas, PostgreSQL, Figma, Node.js, NumPy, Deep Learning'
 'JavaScript, Excel, React, Spring Boot'
 'Spring Boot, GCP, PostgreSQL, ML, Node.js, Excel'
 'PostgreSQL, NumPy, Microservices, ML, Java, Excel'
 'Kubernetes, Deep Learning, MongoDB, PowerBI, Excel'
 'React, MongoDB, System Design' 'Kafka, Tableau, SQL'
 'Pandas, Python, MongoDB' 'AWS, React, Redis, MongoDB, JIRA, Pandas'
 'Deep Learning, PyTorch, PowerBI, Tableau, Redis, MongoDB, SQL'
 'NumPy, Node.js, JIRA, Docker'
 'Spring Boot, JIRA, Tableau, Redis, JavaScript'
 'PostgreSQL, TensorFlow, JIRA, Spring Boot, Deep Learning, Java, System Design'
 'Docker, PyTorch, TensorFlow, Tableau, Agile'
 'Azure, MongoDB, Figma, GCP' 'Azure, TensorFlow, JavaScript, Sketch'
 'Microservices, Azure, Node.js, SQL, Spring Boot, Kubernetes, PostgreSQL'
 'Node.js, AWS, Microservices, Figma, Sketch' 'SQL, JIRA, Azure'
 'MongoDB, Python, PostgreSQL, Kubernetes'
 'PostgreSQL, Tableau, Java, Kafka, Spring Boot, PowerBI, Agile'
 'Kubernetes, PostgreSQL, React, Redis'
 'PostgreSQL, Azure, Excel, Java, SQL, React' 'Agile, MongoDB, SQL'
 'TensorFlow, Python, Microservices, NumPy'
 'PowerBI, Tableau, Kafka, Redis'
 'Java, MongoDB, PostgreSQL, Kubernetes, PyTorch, Node.js, Microservices'
 'NumPy, Tableau, Deep Learning, Azure, Figma'
 'Spring Boot, Agile, PostgreSQL, MongoDB, Python'
 'JavaScript, Python, Kubernetes, Spring Boot, AWS'
 'Redis, JavaScript, Pandas, React, Java, Spring Boot, Docker'
 'Deep Learning, Docker, PowerBI, PyTorch, Sketch, Figma'
 'PowerBI, Figma, GCP, Deep Learning'
 'Azure, Sketch, Node.js, Docker, GCP, Excel'
 'TensorFlow, MongoDB, Pandas'
 'Microservices, MongoDB, Sketch, Node.js, Excel, PowerBI'
 'Redis, Spring Boot, Tableau' 'Deep Learning, JIRA, Azure, Tableau'
 'SQL, Redis, Excel, NumPy' 'SQL, Node.js, Redis'
 'SQL, Node.js, PowerBI, TensorFlow, Kafka, MongoDB'
 'TensorFlow, JavaScript, PostgreSQL'
 'Pandas, Redis, PowerBI, Tableau, ML'
 'Kafka, GCP, PyTorch, Sketch, MongoDB, React'
 'Tableau, NumPy, JavaScript, Deep Learning, Kubernetes'
 'Kafka, Tableau, GCP, JIRA' 'MongoDB, Redis, Excel'
 'ML, Excel, System Design, Sketch, Azure'
 'NumPy, React, Tableau, MongoDB'
 'PowerBI, Deep Learning, Kafka, System Design, Agile'
 'React, Kafka, Redis' 'PyTorch, Node.js, Sketch'
 'Pandas, Sketch, Azure, NumPy, AWS, Deep Learning'
 'NumPy, Figma, Kubernetes, Spring Boot, PyTorch'
 'Kubernetes, PyTorch, Microservices, Azure, System Design, Sketch, Spring Boot'
 'JavaScript, Python, PyTorch' 'Spring Boot, ML, PowerBI, Microservices'
 'Python, Excel, SQL, Tableau, Redis, JavaScript'
 'AWS, SQL, Redis, Pandas, GCP'
 'MongoDB, TensorFlow, Redis, JavaScript, Pandas'
 'Azure, Python, PowerBI, Sketch, Figma, Pandas, GCP'
 'TensorFlow, MongoDB, Kafka, Python, Kubernetes'
 'Sketch, GCP, System Design' 'Docker, Azure, Microservices'
 'PostgreSQL, Microservices, Redis' 'Tableau, SQL, Docker'
 'Deep Learning, SQL, Spring Boot, Microservices, GCP, Sketch'
 'Deep Learning, Sketch, Redis, TensorFlow'
 'Redis, Java, Pandas, Kubernetes, Figma, JavaScript'
 'JavaScript, MongoDB, SQL, Java, JIRA, ML, PyTorch'
 'PostgreSQL, Node.js, JIRA, Figma, Sketch, JavaScript'
 'Figma, JavaScript, Sketch, Python, Node.js, Redis, Docker'
 'Spring Boot, Pandas, System Design'
 'JavaScript, PostgreSQL, Spring Boot' 'Java, Pandas, PowerBI, SQL'
 'GCP, Azure, Excel, PowerBI' 'JavaScript, MongoDB, React'
 'AWS, Spring Boot, Kubernetes, Agile, Microservices, System Design, GCP'
 'JIRA, Agile, Sketch, Redis, AWS, JavaScript'
 'Kafka, Excel, Deep Learning, Tableau, Azure' 'System Design, Kafka, SQL'
 'Tableau, Spring Boot, Kafka, Redis, System Design, JavaScript, PostgreSQL'
 'AWS, PyTorch, Azure'
 'PowerBI, Microservices, Spring Boot, NumPy, Kafka, Tableau'
 'MongoDB, Spring Boot, Excel, SQL, Deep Learning, Python'
 'GCP, Redis, SQL, System Design, Agile, Deep Learning, Python'
 'AWS, Sketch, PostgreSQL' 'Agile, PowerBI, React, AWS, Kafka'

In [111]:
# Employees with AWS skill

aws=df[df["Skills"].str.contains("AWS",case=False,na=False)]

# Employees without AWS skill
no_aws=df[~df["Skills"].str.contains("AWS",case=False,na=False)]

print("Median CTC with AWS")
print(aws["current_CTC_clean"].median())

print("Median CTC without AWS")
print(no_aws["current_CTC_clean"].median())

Median CTC with AWS
23.8
Median CTC without AWS
21.4

In [113]:
# Remove ₹ symbol
df["currenct_ctc"] = df["currenct_ctc"].astype(str).str.replace("₹","", regex=False)

# Remove LPA text
df["currenct_ctc"] = df["currenct_ctc"].str.replace("LPA","", regex=False)

# Remove commas
df["currenct_ctc"] = df["currenct_ctc"].str.replace(",","", regex=False)

# Remove extra spaces
df["currenct_ctc"] = df["currenct_ctc"].str.strip()

# Convert to numeric
df["currenct_ctc"] = pd.to_numeric(df["currenct_ctc"], errors="coerce")

/tmp/ipykernel_1081/998560240.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].astype(str).str.replace("₹","", regex=False)
/tmp/ipykernel_1081/998560240.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.replace("LPA","", regex=False)
/tmp/ipykernel_1081/998560240.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.replace(",","", regex=False)
/tmp/ipykernel_1081/998560240.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.strip()
/tmp/ipykernel_1081/998560240.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = pd.to_numeric(df["currenct_ctc"], errors="coerce")

In [114]:
print(df["currenct_ctc"].dtype)

float64

In [115]:
# Median salary by company type
company = df.groupby("company_type")["currenct_ctc"].median()

print(company)

company_type
Early-stage    20.65
MNC            24.70
Mid-size       21.90
Unicorn        31.30
Name: currenct_ctc, dtype: float64

In [116]:
# Clean the Current CTC column

df["currenct_ctc"] = df["currenct_ctc"].astype(str)

df["currenct_ctc"] = df["currenct_ctc"].str.replace("₹","",regex=False)
df["currenct_ctc"] = df["currenct_ctc"].str.replace("LPA","",regex=False)
df["currenct_ctc"] = df["currenct_ctc"].str.replace(",","",regex=False)
df["currenct_ctc"] = df["currenct_ctc"].str.strip()

df["currenct_ctc"] = pd.to_numeric(df["currenct_ctc"],errors="coerce")

# Convert salary in rupees to LPA
df.loc[df["currenct_ctc"]>1000,"currenct_ctc"]=df.loc[df["currenct_ctc"]>1000,"currenct_ctc"]/100000

print(df["currenct_ctc"].head())

0    49.4
1     9.7
2    33.6
3    41.4
4    36.4
Name: currenct_ctc, dtype: float64

/tmp/ipykernel_1081/4086117633.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].astype(str)
/tmp/ipykernel_1081/4086117633.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.replace("₹","",regex=False)
/tmp/ipykernel_1081/4086117633.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.replace("LPA","",regex=False)
/tmp/ipykernel_1081/4086117633.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.replace(",","",regex=False)
/tmp/ipykernel_1081/4086117633.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = df["currenct_ctc"].str.strip()
/tmp/ipykernel_1081/4086117633.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["currenct_ctc"] = pd.to_numeric(df["currenct_ctc"],errors="coerce")

In [117]:
# Find median salary for each company type

company_salary=df.groupby("company_type")["currenct_ctc"].median()

print(company_salary)

company_type
Early-stage    17.2
MNC            22.1
Mid-size       20.1
Unicorn        27.6
Name: currenct_ctc, dtype: float64

In [119]:
# Calculate median salary for each role

role_median=df.groupby('Role ')["currenct_ctc"].transform("median")

# Difference between employee salary and role median

df["salary_gap"]=role_median-df["currenct_ctc"]

# Top 10 underpaid employees

underpaid=df.sort_values(by="salary_gap",ascending=False).head(10)

print(underpaid[["employee_id",'Role ',"currenct_ctc","salary_gap"]])

    employee_id             Role   currenct_ctc  salary_gap
233     BLR0459  Backend Engineer           9.9        21.2
364     BLR0750             Sr PM          10.8        20.7
962     BLR0997      Product Lead          12.0        19.1
104     BLR0507   Product Manager          13.8        17.6
13      BLR0989       ML Engineer          10.0        17.5
14      BLR0782   Product Manager          14.2        17.2
938     BLR0525  Backend Engineer          14.8        16.3
884     BLR0871       ML Engineer          11.2        16.3
597     BLR0005             Sr PM          15.4        16.1
698     BLR0888    UI/UX Designer           6.2        15.8

/tmp/ipykernel_1081/1438005783.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["salary_gap"]=role_median-df["currenct_ctc"]

In [126]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print(df.columns)

Index(['employee_id', 'Role', 'years_exp', 'currenct_ctc', 'previous_ctc',
       'comapny', 'company_type', 'Skills', 'location', 'education_tier',
       'joining_year', 'work_mode', 'current_CTC_clean', 'previous_CTC_Clean',
       'salary_gap'],
      dtype='object')

In [131]:
# Task 4 - Build the Final Printed Report

print("="*70)
print("           BANGALORE TECH SALARY DECODER")
print("      Built by Parinitha R | The Unlox Academy")
print("="*70)

print("\nDataset : Bangalore Tech Salary Dataset")
print("Period  : 2024 Employment Snapshot")

print("\n" + "-"*70)
print("MEDIAN CTC BY ROLE")
print("-"*70)

role_report = df.groupby('Role')["currenct_ctc"].median().sort_values(ascending=False)

for role, salary in role_report.items():
    print(f"{role:<25} {salary:.2f} LPA")


print("\n" + "-"*70)
print("SDE BACKEND CTC BY EXPERIENCE")
print("-"*70)

sde = df[df['Role'] == "SDE Backend"].copy()

bins=[0,1,3,5,100]
labels=["0-1","2-3","4-5","6+"]

sde.loc[:, "Experience_Group"] = pd.cut(
    sde["years_exp"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

exp_report=sde.groupby("Experience_Group", observed=False)["currenct_ctc"].median()

for exp, salary in exp_report.items():
    print(f"{exp:<10} {salary:.2f} LPA")


print("\n" + "-"*70)
print("COMPANY TYPE MEDIAN SALARY")
print("-"*70)

company_report=df.groupby("company_type")["currenct_ctc"].median()

for company,salary in company_report.items():
    print(f"{company:<20} {salary:.2f} LPA")


print("\n" + "-"*70)
print("TOP 5 UNDERPAID PROFESSIONALS")
print("-"*70)

top5=underpaid.head(5)

for index,row in top5.iterrows():
    print(f"{row['employee_id']:<10} {row['Role ']:<20} {row['currenct_ctc']:.2f} LPA")


print("="*70)
print("END OF REPORT")
print("="*70)

======================================================================
           BANGALORE TECH SALARY DECODER
      Built by Parinitha R | The Unlox Academy
======================================================================

Dataset : Bangalore Tech Salary Dataset
Period  : 2024 Employment Snapshot

----------------------------------------------------------------------
MEDIAN CTC BY ROLE
----------------------------------------------------------------------
Sr PM                     31.50 LPA
Product Manager           31.40 LPA
Product Lead              31.10 LPA
Backend Engineer          31.10 LPA
ML Engineer               27.50 LPA
Data Science Engineer     25.65 LPA
FE                        25.30 LPA
SDE FS                    24.60 LPA
Fullstack Dev             24.55 LPA
Frontend Developer        24.30 LPA
Infra Engineer            23.45 LPA
SDE Full-Stack            23.05 LPA
Data Scientist            22.85 LPA
Site Reliability Engineer 22.20 LPA
UI/UX Designer            22.00 LPA
SDE Backend               21.60 LPA
DevOps Engineer           21.50 LPA
Analytics Engineer        21.40 LPA
Frontend Engineer         21.00 LPA
Business Systems Analyst  20.90 LPA
SDE-Backend               20.60 LPA
Full Stack Engineer       20.50 LPA
BA                        20.50 LPA
Frontend Dev              20.25 LPA
UI Designer               19.50 LPA
SDE Frontend              19.20 LPA
Product Designer          19.00 LPA
Backend Dev               18.00 LPA
UX Designer               18.00 LPA
Designer                  17.90 LPA
FullStack                 17.60 LPA
BI Analyst                16.45 LPA
Backend Developer         16.40 LPA
Business Analyst          16.40 LPA
Data Analyst              16.30 LPA
SDE-Frontend              16.25 LPA

----------------------------------------------------------------------
SDE BACKEND CTC BY EXPERIENCE
----------------------------------------------------------------------
0-1        11.65 LPA
2-3        21.40 LPA
4-5        25.20 LPA
6+         36.20 LPA

----------------------------------------------------------------------
COMPANY TYPE MEDIAN SALARY
----------------------------------------------------------------------
Early-stage          17.20 LPA
MNC                  22.10 LPA
Mid-size             20.10 LPA
Unicorn              27.60 LPA

----------------------------------------------------------------------
TOP 5 UNDERPAID PROFESSIONALS
----------------------------------------------------------------------
BLR0459    Backend Engineer     9.90 LPA
BLR0750    Sr PM                10.80 LPA
BLR0997    Product Lead         12.00 LPA
BLR0507    Product Manager      13.80 LPA
BLR0989    ML Engineer          10.00 LPA
======================================================================
END OF REPORT
======================================================================

In [132]:
# task 5 insights
print("KEY INSIGHTS")
print("1. The role with the highest median salary was Sr PM at 31.50 LPA.")
print("2. SDE Backend professionals with 6+ years of experience earned much higher salaries than freshers.")
print("3. Unicorn companies offered higher median salaries than MNCs for the same role.")

KEY INSIGHTS
1. The role with the highest median salary was Sr PM at 31.50 LPA.
2. SDE Backend professionals with 6+ years of experience earned much higher salaries than freshers.
3. Unicorn companies offered higher median salaries than MNCs for the same role.

In [ ]:
# Task 1 - Load and Inspect Dataset
# Task 2 - Data Cleaning
# Task 3 - Business Questions
# Task 4 - Final Printed Report
# Task 5 - Key Insights